"""Initial schema

Revision ID: 3a72552c6152
Revises: 
Create Date: 2026-07-15 14:36:42.239761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a72552c6152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('entities',
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=False),
    sa.Column('parent_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_key')
    )
    op.create_table('metrics_daily',
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('conv_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_key'], ['entities.entity_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_key', 'date')
    )
    op.create_index('idx_metrics_daily_account_level_date', 'metrics_daily', ['account_id', 'level', 'date'], unique=False)
    op.create_index('idx_metrics_daily_provider_date', 'metrics_daily', ['provider', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metrics_daily_provider_date', table_name='metrics_daily')
    op.drop_index('idx_metrics_daily_account_level_date', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_table('entities')
    op.drop_table('accounts')
    # ### end Alembic commands ###
